require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'coverage/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# Disable all Capybara cops (not using Capybara)
Capybara:
  Enabled: false

Capybara/RSpec:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Disable all FactoryBot cops (not using FactoryBot)
FactoryBot:
  Enabled: false

# Disable all RSpecRails cops (not a Rails app)
RSpecRails:
  Enabled: false

RSpecRails/AvoidSetupHook:
  Enabled: false

RSpecRails/HaveHttpStatus:
  Enabled: false
  Exclude:
    - '**/*'

RSpecRails/HttpStatus:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpecRails/MinitestAssertions:
  Enabled: false

RSpecRails/NegationBeValid:
  Enabled: false

RSpecRails/TravelAround:
  Enabled: false
