require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'coverage/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# Not a Rails app - disable Rails-specific cops
RSpecRails/HaveHttpStatus:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

# File naming convention doesn't match module structure
RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
