apiVersion: v1
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
    prometheusK8s:
      retention: 24h
      volumeClaimTemplate:
        metadata:
          name: prometheus-storage
        spec:
          resources:
            requests:
              storage: 1Gi
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
