apiVersion: v1
kind: Service
metadata:
  labels:
    app: crypto
  name: crypto
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: crypto
    deploymentconfig: crypto
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
