apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: asset-monitoring
  namespace: monitoring-example
  labels:
    app: asset-monitoring
    app.kubernetes.io/name: asset-monitoring
spec:
  selector:
    matchLabels:
      app: asset-monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
      scrapeTimeout: 10s
