apiVersion: v1
kind: Service
metadata:
  name: asset-monitoring
  namespace: monitoring-example
  labels:
    app: asset-monitoring
    app.kubernetes.io/name: asset-monitoring
    app.kubernetes.io/version: "1.0.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: asset-monitoring
  sessionAffinity: None
